### ISSUE TITLE
Upload fails due to parse error

### ISSUE THREAD

**Issue by mammuth** [jakoch/csgo-cli#1] opened 2019-03-21 17:25 UTC
Running `csgo_cli -matches -upload` yields the following errors. The past matches are recognized correctly, but the upload to csgostats.gg fails.

Maybe an API change by csgostats.gg?

```
 Uploading Demo ShareCodes to https://csgostats.gg/:

Error(offset 0): Invalid value.
<

Error: Could not parse the response (to the demo sharecode POST request).
```

**Comment by mammuth** [comment] 2019-03-21 17:39
When posting a match on the website itself, a response looks like this:

```
{
	"status": "complete",
	"data": {
		"msg": "Complete - <a href=\"\/match\/3838420\">View<\/a>",
		"index": "0",
		"sharecode": "CSGO-8vzEY-Q7xwY-eiA65-sNFTh-Vt3NF",
		"queue_id": 3891684,
		"demo_id": 3838420,
		"url": "https:\/\/csgostats.gg\/match\/3838420"
	},
	"error": 0
}
```

Maybe they didn't return HTML in `data.msg` before? (because the msg contains the "invalid value" `<`.
However the response seems to be valid JSON,

**Comment by jakoch** [comment] 2019-03-21 23:55
Hey! Thank you for reporting the issue. 

> Maybe an API change by csgostats.gg?

Yes. Seems the response content for the POST request changed somehow.
I should probably add a "-verbose" mode to the CLI for easier debugging (printing the raw reponse content). For now i have to recompile and take a look at the reponse in manual debug mode: https://github.com/jakoch/csgo-cli/blob/master/src/ShareCodeUpload.h#L119

Some notes:
- The file containing the logic for uploading the ShareCode is [ShareCodeUpload.h](https://github.com/jakoch/csgo-cli/blob/master/src/ShareCodeUpload.h)
- [uploadShareCode()](https://github.com/jakoch/csgo-cli/blob/7772f3c944c0ebf50a5a638835e4f2ea4a624a08/src/ShareCodeUpload.h#L32) uses curl to POST the ShareCode
- The reponse is then parsed by [processJsonResponse()](https://github.com/jakoch/csgo-cli/blob/7772f3c944c0ebf50a5a638835e4f2ea4a624a08/src/ShareCodeUpload.h#L125)
- There are 3 response types: error, queued, complete. See [testProcessJsonResponse()](https://github.com/jakoch/csgo-cli/blob/7772f3c944c0ebf50a5a638835e4f2ea4a624a08/src/ShareCodeUpload.h#L188)

**Comment by jakoch** [comment] 2019-03-25 12:56
Update by csgostats.gg on this matter: https://twitter.com/csgostatsgg/status/1104705898801446918

**Comment by mammuth** [comment] 2019-03-25 14:45
> Update by csgostats.gg on this matter: https://twitter.com/csgostatsgg/status/1104705898801446918

Ah, good catch. 

Did you already log their full response? (Seems like they introduced some rate limiting or something like that).

**Comment by jakoch** [comment] 2019-03-25 16:56
> Did you already log their full response?

Yes, the reponse is the Cloudflare "Please fill this captcha" HTML page.

My idea to solve the issue is to use curl_easy_reset() on an existing curl handle.
Basically doing a two-step request to simulate browser behaviour.

Firstly, a GET request to csgostats.gg, then keeping the curl handle alive.
This means access to the live connection, Session ID cache, DNS cache, and most important to the cookies. So that, secondly, the following POST request can re-use the cloudflare cookie (`__cfduid`).

But at the moment, i'm still working on updating dependencies (curl, protobuf, csgo protobufs, steamworks sdk) and getting everything working again with the newer versions.

**Comment by jakoch** [comment] 2019-03-28 22:48
It seems, that sending an additional "accept-language" header does the trick.

Here is the latest development build for testing: https://ci.appveyor.com/api/buildjobs/4fq2p12x6ppl9j6c/artifacts/csgo-cli.zip
Thank you for feedback.

**Comment by mammuth** [comment] 2019-03-29 19:33
The log doesn't show matches and matches are also not submitted (but there is no error or something the like).

![Capture](https://user-images.githubusercontent.com/3121306/55255305-9614f180-525a-11e9-9b72-d8b24d5d2660.PNG)

**Comment by jakoch** [comment] 2019-03-29 19:37
Thank you for feedback.
Crap. Hard to test, because i'm currently not playing CS:GO. So i have no new matches in my user profile.

What about `csgo_cli -user`? Do you get data displayed?

**Comment by mammuth** [comment] 2019-03-29 20:27
`csgo_cli -user` works fine.

```
$ csgo_cli -matches -upload -verbose
LOG:[ Start ] STEAM_INIT
Setting breakpad minidump AppID = 730
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561198082458634 [API loaded no]
LOG:[ End   ] STEAM_INIT
LOG:[ Start ] CallbackThread & Steam_RunCallbacks
LOG:[ End   ] CallbackThread & Steam_RunCallbacks
LOG:[ Start ] Trying to establish a GameClient Connection
LOG:          Requesting: GameClient Connection
LOG:          Successful: GameClient connected!
LOG:[ End   ] Trying to establish a GameClient Connection
LOG:[ Start ] [ Thread ] MatchList
LOG:requesting MatchList
LOG:got MatchList
LOG:[ Start ] processing MatchList
LOG:[ Start ] processing Match
LOG:[ End   ] processing Match
LOG:[ Start ] processing Match
LOG:[ End   ] processing Match
LOG:[ Start ] processing Match
LOG:[ End   ] processing Match
LOG:[ Start ] processing Match
LOG:[ End   ] processing Match
LOG:[ Start ] processing Match
LOG:[ End   ] processing Match
LOG:[ Start ] processing Match
LOG:[ End   ] processing Match
LOG:[ Start ] processing Match
LOG:[ End   ] processing Match
LOG:[ Start ] processing Match
LOG:[ End   ] processing Match
LOG:[ End   ] processing MatchList
LOG:[ End   ] [ Thread ] MatchList

Hello MAMMUTH!

Here are your latest matches:
```
But still no matches listed.

**Comment by mammuth** [comment] 2019-03-31 14:22
The latest commit (https://github.com/jakoch/csgo-cli/commit/9d8b6b0dfa6a84afe3adb36b6c8af218c9cfc7f5 "output match table, referencing") doesn't print the match table either. 🤔 

![Capture](https://user-images.githubusercontent.com/3121306/55290235-fded4880-53d0-11e9-98cf-bc53ffb7f410.PNG)

**Comment by jakoch** [comment] 2019-04-01 16:35
Ok. Good news! 
I got the curl upload working again using the two request strategy (GET for cookies, then POST).

I added a new CLI command `-sharecode`, short just `-s`, which accepts a single sharecode from the CLI and uploads it to csgostats. I've also added `-verbose` to the curl handling, to see whats going on with the two requests. This works standalone without contacting or initalizing the STEAM API.

Example:
- first run: posting a new sharecode, we get status queued from csgostats
- second run, status: still in queue
- third run, status: complete
```
D:\2-github.com\csgo-cli\build>csgo_cli -sharecode CSGO-8iHiJ-GZRZt-s3Eb2-BPpFp-EE5qB

 Uploading Demo ShareCode to https://csgostats.gg/:
 queued   | 3946168 | https://csgostats.gg/match/processing/3946168 |  in Queue #24 Time Remaining 11m 5s

D:\2-github.com\csgo-cli\build>csgo_cli -s CSGO-8iHiJ-GZRZt-s3Eb2-BPpFp-EE5qB

 Uploading Demo ShareCode to https://csgostats.gg/:
 queued   | 3946168 | https://csgostats.gg/match/processing/3946168 |  Parsing Demo Time Remaining 30s

D:\2-github.com\csgo-cli\build>csgo_cli -s CSGO-8iHiJ-GZRZt-s3Eb2-BPpFp-EE5qB

 Uploading Demo ShareCode to https://csgostats.gg/:
 complete | 3946168 | https://csgostats.gg/match/3892508
```

Download: https://ci.appveyor.com/api/buildjobs/dn7rrwresckyei61/artifacts/csgo-cli.zip

---

Todo:
- [x] sharecode uploading
- [ ] print latest matches table
- [ ] upload sharecodes for latest matches

**Comment by mammuth** [comment] 2019-04-01 20:07
I can confirm that `-sharecode` works. 👍

>Still not sure, if -matches -upload works now.

 `csgo_cli -matches -upload` doesn't work yet.

**Comment by jakoch** [comment] 2019-04-03 23:19
Ok, i played a match and debugged the match table printing.
Here's another dev-build for testing:
https://ci.appveyor.com/api/buildjobs/hkrd8mfpapylvs4h/artifacts/csgo-cli.zip

**Comment by mammuth** [comment] 2019-04-04 15:25
> Ok, i played a match and debugged the match table printing.

Cool! :tada: 

I tested it with the latest commit (https://github.com/jakoch/csgo-cli/commit/64dc41d5db7bac28d3661cb94814eb58286bb361) and the printing of the matches works partlynow. 
A remaining issue is, that all maps are displayed as `?`

`csgo_cli -matches -upload` doesn't upload a match I played. Log: https://pastebin.com/dvscZHTM

**Comment by jakoch** [comment] 2019-04-04 16:13
> csgo_cli -matches -upload doesn't upload a match I played

Thanks for testing and posting the verbose output.
Looks like an SSL issue after posting the sharecode of the first match.
Let's see if SSL_VERIFYHOST with default settings does the trick.
Rebuilding...

> A remaining issue is, that all maps are displayed as ?

Yes... that's sad. But i have no clue where the name of the map hides in the match data!
I'm open for suggestions here.

I looked through the full debug output of matchList and watchableMatchInfo and couldn't find any trace of a map name. The mapname is a header value of the demo/replay file itself. 

The in-game match scoreboard display has the final roundstats (scoreboard) and the match name, right? I believe that the map name data is carried over from the matchmaking process and then combined with the roundstats.

**Comment by jakoch** [comment] 2019-06-18 21:57
I'm closing this one.
Because we are done with the main issues, except for the "display map name" issue.

Thank you for your feedback! 👍 It was very helpful in debugging and fixing stuff.
Please feel free to open a new issue, when you are running into new problems.

**Closed by jakoch** 2019-06-18 21:57 UTC
